source config.sh

docker cp $BACKUP_DIR/$BACKUP_FILE_NAME $CONTAINER_NAME:$LOCAL_BACKUP_DIR/$BACKUP_FILE_NAME
docker exec $CONTAINER_NAME sh -c "mysqlsh -u$USER -p$PASSWORD < $LOCAL_BACKUP_DIR/$BACKUP_FILE_NAME <<EOF
    SHOW DATABASES;
EOF"